# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  displayName: 'Build application'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    repository: '$(imageName)'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: ECRPushImage@1
  inputs:
    awsCredentials: 'aws_ecr_connection'
    regionName: 'eu-central-1'
    imageSource: 'imageid'
    sourceImageId: '$(imageName):$(Build.BuildId)'
    repositoryName: '$(repoName)'
    pushTag: '$(Build.BuildId)'
    forceDockerNamingConventions: true
    logRequest: true
    logResponse: true